#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:/home/gregstoll/extraspace/programs/gwt-linux-1.4.60/gwt-user.jar:/home/gregstoll/extraspace/programs/gwt-linux-1.4.60/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.gregstoll.cluesolver.ClueSolver/ClueSolver.html;
